{{ if and (not .Values.pvc_exists) .Values.jupyter_pvc }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Values.jupyter_pvc}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.jupyter_pvc_capacity}} 
{{ end }}
