apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template: 
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        command: ["/bin/bash","-c","./setup_backend_host.sh && nginx -g 'daemon off;'"]
        env:
        - name: "BACKEND_HOST"
          value: {{ .Release.Name }}-backend
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
