apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template: 
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: '{{ .Values.image.repository }}:{{ .Values.tag }}'
        command: ["nginx","-g", "daemon off;"]
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}