apiVersion: v1
kind: Pod
metadata:
  name: {{.Values.pod_name}}
  namespace: default
spec:
  containers:
  - name: container-test
    image: {{.Values.container}}
    command: ["{{.Values.shell}}", "-c", "{{.Values.test_cmd}}"]
  restartPolicy: Never
